import { test } from 'node:test';
import assert from 'node:assert/strict';
import { calculateRank } from './rank';

test('reproduces the B+ rank of the last card generated by github-readme-stats', () => {
  const rank = calculateRank({
    commits: 988,
    prs: 297,
    issues: 8,
    reviews: 0,
    stars: 23,
    followers: 7,
  });

  assert.equal(rank.level, 'B+');
  // The old card drew its ring with stroke-dashoffset 111.152 of a 251.327 circumference.
  assert.ok(Math.abs(rank.percentile - 44.2257) < 0.001, `percentile was ${rank.percentile}`);
});

test('gives the lowest level to an empty profile', () => {
  const rank = calculateRank({ commits: 0, prs: 0, issues: 0, reviews: 0, stars: 0, followers: 0 });

  assert.deepEqual(rank, { level: 'C', percentile: 100 });
});

test('gives the top level to an outstanding profile', () => {
  const rank = calculateRank({
    commits: 10000,
    prs: 5000,
    issues: 2000,
    reviews: 1000,
    stars: 1000000,
    followers: 100000,
  });

  assert.equal(rank.level, 'S');
});
